version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: task-1
      POSTGRES_USER: balaji
      POSTGRES_PASSWORD: Balaji%40sq1
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "balaji", "-d", "task-1"]
      interval: 5s
      timeout: 3s
      retries: 5

  qdrant:
    image: qdrant/qdrant:v1.2.0
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6333 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  streamlit:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://balaji:Balaji%40sq1@postgres:5432/task-1"
      QDRANT_URL: "http://qdrant:6333"
      OLLAMA_API: "http://ollama:11434"
    ports:
      - "8501:8501"
    command: streamlit run app.py

volumes:
  postgres_data:
  qdrant_data:
  ollama_data:
