version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrantdata:/qdrant/storage

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: llama2
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - postgres
      - qdrant
      - ollama
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      # Add PYTHONPATH so imports work inside container
      PYTHONPATH: /app
      # Streamlit config environment variables
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_SERVER_ENABLECORS: "false"
      STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
      STREAMLIT_SERVER_PORT: "8501"
    entrypoint: ["/entrypoint.sh"]

volumes:
  pgdata:
  qdrantdata:
  ollama_data:
